server:
  port: 8084
  forward-headers-strategy: framework
spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://name:password@172.20.146.73:8888