services:
  bookkeeping:
    uri: lb://bookkeeping-service
    registration-id: keycloak

  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.20.146.73:8082/realms/digital-bookkeeping
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: librarian-app
            client-secret: twqt30F7zVKXfTeGZDTjXouWn1RsEHd7
            scope:
              - openid
              - view_library
              - edit_library
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: librarian-app
            client-secret: twqt30F7zVKXfTeGZDTjXouWn1RsEHd7
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: librarian-app
            client-secret: twqt30F7zVKXfTeGZDTjXouWn1RsEHd7
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://172.20.146.73:8082/realms/digital-bookkeeping
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.20.146.73:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.3
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/