server:
  port: 8081

services:
  bookkeeping:
    uri: http://localhost:8080
    registration-id: keycloak

spring:
  boot:
    admin:
      client:
        url: http://localhost:8083
        instance:
          name: librarian-app
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/digital-bookkeeping
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: librarian-app
            client-secret: twqt30F7zVKXfTeGZDTjXouWn1RsEHd7
            scope:
              - openid
              - view_library
              - edit_library
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: librarian-app
            client-secret: twqt30F7zVKXfTeGZDTjXouWn1RsEHd7
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/digital-bookkeeping
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'