server:
  port: 8080

spring:
  application:
    name: bookkeeping-service
  boot:
    admin:
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/bookkeeping-db
    username: librarian
    password: librarian
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.146.73:8082/realms/digital-bookkeeping
      client:
        provider:
          keycloak:
            issuer-uri: http://172.20.146.73:8082/realms/digital-bookkeeping
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bookkeeping-service
            client-secret: OXtKlZ844xE9MtcMmUqJ76zmryQ9lKQH
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: bookkeeping-service
            client-secret: OXtKlZ844xE9MtcMmUqJ76zmryQ9lKQH
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://172.20.146.73:9411/api/v2/spans
  tracing:
    sampling:
      probability: 0.3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true