server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookkeeping-db
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/digital-bookkeeping
