server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bookkeeping-db
    username: librarian
    password: librarian
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.0.1:8082/realms/digital-bookkeeping
      client:
        provider:
          keycloak:
            issuer-uri: http://172.17.0.1:8082/realms/digital-bookkeeping
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bookkeeping-service
            client-secret: OXtKlZ844xE9MtcMmUqJ76zmryQ9lKQH
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: bookkeeping-service
          service-host-type: ip
        url: http://localhost:8083
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'